
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

---
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6378:6378"

networks:
  default:
    driver: bridge
  my-network: