version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      - my-network

  mysql_2:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql_2/:/var/lib/mysql
      - ./dummy/:/docker-entrypoint-initdb.d
      - ./dummy/csv/:/dummy/csv/
    user: "999:999"
    command: --secure-file-priv=
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  redis_2:
    image: redis
    container_name: redis
    ports:
      - "6378:6378"

networks:
  my-network:
    driver: bridge